# Generated by Django 4.1.6 on 2023-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_order',
            field=models.DateTimeField(null=True),
        ),
    ]
