# Generated by Django 4.1.6 on 2023-04-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_last_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
