# Generated by Django 4.1.6 on 2023-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_customer_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='zip_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
