# Generated by Django 4.1.6 on 2023-04-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='desciption',
            new_name='description',
        ),
    ]
