# Generated by Django 4.1.6 on 2023-04-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_menuitem_description_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
