# Generated by Django 4.1.6 on 2023-04-16 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 21, 23, 29, 826680), verbose_name='Payment Date'),
        ),
        migrations.DeleteModel(
            name='OrderCoupon',
        ),
    ]
