# Generated by Django 4.1.6 on 2023-04-24 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(null=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 13, 59, 8, 893906), verbose_name='Payment Date'),
        ),
    ]
