# Generated by Django 4.1.6 on 2023-04-24 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_order_order_date_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 14, 2, 46, 713114), verbose_name='Payment Date'),
        ),
    ]
