# Generated by Django 4.1.6 on 2023-04-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
