# Generated by Django 4.1.6 on 2023-04-16 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_order_status_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Not Paied', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 18, 23, 44, 78961), verbose_name='Payment Date'),
        ),
    ]
