# Generated by Django 4.1.6 on 2023-04-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.customer'),
            preserve_default=False,
        ),
    ]
