# Generated by Django 4.1.6 on 2023-04-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_category_menuitem_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
