# Generated by Django 4.1.6 on 2023-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_deliveryaddress_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.URLField(default='', verbose_name='Menu Item Image'),
            preserve_default=False,
        ),
    ]
